# by Paulo
version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=LosReactivos
      - POSTGRES_PASSWORD=DBEscuela12!#
    ports:
      - '6543:5432'
    volumes: 
      - ./DB_Escuela:/var/lib/postgresql/data