# by Paulo
version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=LosReactivos
      - POSTGRES_PASSWORD=DBEscuela12!#
    ports:
      - '5432:5432'
    volumes: 
      - ./DB_Escuela:/var/lib/postgresql/data